# Generated by Django 2.2 on 2019-04-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('username', models.CharField(help_text='客户姓名', max_length=100, verbose_name='客户姓名')),
                ('email', models.EmailField(help_text='客户邮箱', max_length=254, null=True, verbose_name='客户邮箱')),
                ('telephone', models.CharField(error_messages={'unique': '此手机号码已经注册'}, help_text='客户手机号码', max_length=11, unique=True, verbose_name='客户手机号码')),
                ('content', models.TextField(help_text='留言内容', verbose_name='留言内容')),
            ],
            options={
                'verbose_name_plural': '客户留言',
                'db_table': 'tb_client_word',
                'verbose_name': '客户留言',
                'ordering': ['-create_time', '-id'],
            },
        ),
    ]
