# Generated by Django 2.2 on 2019-04-18 08:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('image_url', models.URLField(help_text='图片URL', verbose_name='图片URL')),
                ('priority', models.IntegerField(choices=[(1, '第一级'), (2, '第二级'), (3, '第三级'), (4, '第四级'), (5, '第五级'), (6, '第六级')], default=6, help_text='优先级', verbose_name='优先级')),
                ('link_to', models.URLField(help_text='链接', verbose_name='链接')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['priority', '-update_time', '-id'],
                'db_table': 'tb_banner',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(max_length=100, verbose_name='产品分类')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='product.ProductCategory', verbose_name='一级分类')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'ordering': ['-update_time', '-id'],
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('brand', models.CharField(help_text='产品品牌', max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='产品品牌')),
                ('thumbnail', models.URLField(default='', help_text='图片URL', verbose_name='图片URL')),
                ('version', models.CharField(max_length=200, verbose_name='产品型号')),
                ('describe', models.CharField(help_text='产品描述', max_length=200, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='产品描述')),
                ('clicks', models.IntegerField(default=0, help_text='点击量', verbose_name='点击量')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.ProductCategory', verbose_name='产品分类')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
                'ordering': ['-update_time', '-id'],
                'db_table': 'tb_products',
            },
        ),
    ]
